### ISSUE TITLE
Performance concerns

### ISSUE THREAD

**Issue by enobufs** [pion/logging#10]
pion/logging has been really useful for me, and using a lot for debugging.
@Sean-Der expressed his concern about its performance, and I'd agree, that is a concern...

For example, if you have this statement:
```go
	logger.Debug("received data %s", pkt.String())
```

It looks alright, and it is just a debug log that only prints out when it is enabled with PION_LOG_DEBUG...

BUT! What if `pkt.String()` was an expensive routine? This is evaluated no matter what, consuming CPU time in production as well... Unfortunately, go has no compile-time options like C has (#ifdef etc.)

One obvious solution would be to use a callback like this:
```go
	logger.Debug(func (p *LoggerPad) {
		p.Format("received data %s", pkt.String())
	})
```

The Debug function can be designed in a way that the callback function passed in it won't be called if it is not set to DEBUG level. You will need to type a lot more but it saves a lot of CPU time!

**Comment by hugoArregui** [comment]
1) I miss #ifdefs so much..
2) IMHO I think we are mixing things, one thing is the logging level and the other one is how optimized is your build. For example, you may want to set log level to DEBUG in prod to be able to collect info about a problem, but not necessarily enable this big expensive computation that you don't need. Or, maybe you have an big expensive computation in case of an error (that you log as ERROR) but you choose to enable it only for non release builds. 

In summary I think if we are going to perform some expensive operation that is not related to the actual functionality we should special case it, no matter the log level.

3) Maybe a bit OT but also related to performance. I've been playing with zerolog (https://github.com/rs/zerolog) and although we can adapt or factoring to zerolog, it doesn't really take advantage of the full zerolog perfomance just because the API is so different, for example, we do things like:

```
logger.Debugf("datachannel opened, id: %d", channel.ID())
```

while zerolog will:

```
logger.Debug().Int("datachannelID", channel.ID()).Msg("datachannel opened")
```

Since we avoid varargs we can keep args on stack which is really useful. I'm wondering if we should move to a zerolog like interface instead, because zerolog -> traditional log will still work, but not the other way around.

**Comment by Sean-Der** [comment]
In the future we will move to https://pkg.go.dev/golang.org/x/exp/slog

The Go team has fixed/addressed the concerns in this thread https://pkg.go.dev/golang.org/x/exp/slog#hdr-Performance_considerations
